### ISSUE TITLE
גרפים של 24 שעות

### ISSUE THREAD

**Issue by daniels100** [agrologic-repo/webchick-server#24]
יש שוני בגרפים של 24 שעות בלהקות  גנאדי ואני כתבנו הסבר למטה

**Comment by Genadi77** [comment]
היי ולרי
דויד שטאופר מתלונן על חוסר בגרפים ב24 שעות היסטוריה.
חווה GG-Leuenberger
אתה יכול להכנס אליו ולראות שגרפים לפי שעה בלהקה 2-19
שונים מגרפים בלהקה 3-19 ובלהקות 1-19 
אולי זה יתן לך כיוון.
הוא מתלונן שחסרים המון גרפים.

**Comment by Genadi77** [comment]
כרגע קיבלנו קבצים מהבקר הזה ויוסי אומר להכל בהסטוריה נראה תקין.
אם אתה צריך שנחבר בקר כמו שלו פה בחברה לצורך בדיקות תגיד לי ואנחנו נתקין.
תודה.

**Comment by agrologic-repo** [comment]
@daniels100 האם זה רלוונטי ?

**Comment by daniels100** [comment]
אפשר לסגור , זה מאוד דומה לפניה הקודמת #7
