### ISSUE TITLE
The system is slow

### ISSUE THREAD

**Issue by daniels100** [agrologic-repo/webchick-server#3]
The WEBCHICK vrey slowly 
Some customers see whit page 
Some customers feel slow in the system

**Comment by agrologic-repo** [comment]
ביעה נפתרה לאחר אתחול שרת webchick ושרת mysql

**Comment by daniels100** [comment]
שמנו לב לתופעה מעניינית, בשעות הצהריים יש עומס בבוקר ובערב מערכת עובדת דיי בסדר 
.העומס נוצר כאשר יש יותר מעל 30 משתמשים מחוברים, ואז המערכת ניהית איטית,
מעבר בין דף לדף לוקח הרבה זמן 
כאשר מנסים לצפות בנתוני הלול יש מסך לבן ולאחר מספר דקות הנתונים מופיעים

**Comment by daniels100** [comment]
כנראה כשאני עשיתי אתחול זה היה בשעות "העומס" ואז כשהתחברו יותר מ30 משתמשים המערכת הייתה איטית עדיין 
וכאשר עשית אתחול ביום שישי היה פחות מ30 משתמשים מחוברים ואז המערכת עבדה טוב
