### ISSUE TITLE
בעיית שם תקשורת

### ISSUE THREAD

**Issue by daniels100** [agrologic-repo/webchick-server#31]
לא משנה איזה סוג של בקר בוחרים הוא שולח תמיד בקשה של T901
וגם אי אפשר לערוך את סוג הבקר צריך למחוק את הבקר ולהוסיף אחד מחדש

**Comment by daniels100** [comment]
עדכון מצב הוואבציק כן משנה סוג בקר רק לאחר הוספת בקר חדש וניתוק הסלינג מהרשת ,בעריכה זה לא עובד

**Comment by agrologic-repo** [comment]
@daniels100 

האם זה תקין ? בדוק בבקשה . אם כן תסגור את הבאג .

**Comment by daniels100** [comment]
עובד רק במצב של ניתוק הסלינג וחיבורו מחדש

**Comment by agrologic-repo** [comment]
> עובד רק במצב של ניתוק הסלינג וחיבורו מחדש

זאת התנהגות תקינה . כי אם סלינק מחובר ושולח בקשה אי אפשר לשנות לבקר שם תקשורת.
