### ISSUE TITLE
תוכנה נמחקה בפתאומיות מהוואבציק

### ISSUE THREAD

**Issue by daniels100** [agrologic-repo/webchick-server#33]
לקוח eliplet12-13
התלונן על כך שהוא לא רואה את שצי הלולים שלו
הוא אמר שבטעות התעשק עם ההגדרות וכנראה מחק את הלולים 
שתי דברים מוזרים :
1: שם המשתמש שלו רגיל ולא ADVANCE לכן מוזר שהייתה לו גישה כזה 
2: התוכנה ARI118701 קיימת מ2015 
תוכל לבדוק בDATA BASE בשרת אם יש איזשהוא מידע לגבי מתי התוכנה הזאת נמחקה או משהו שיתן לנו רמז איך זה קרה ?

**Comment by daniels100** [comment]
.

**Comment by agrologic-repo** [comment]
בדקתי 

> לקוח eliplet12-13
> התלונן על כך שהוא לא רואה את שצי הלולים שלו
> הוא אמר שבטעות התעשק עם ההגדרות וכנראה מחק את הלולים
> שתי דברים מוזרים :
> 1: שם המשתמש שלו רגיל ולא ADVANCE לכן מוזר שהייתה לו גישה כזה
> 2: התוכנה ARI118701 קיימת מ2015
> תוכל לבדוק בDATA BASE בשרת אם יש איזשהוא מידע לגבי מתי התוכנה הזאת נמחקה או משהו שיתן לנו רמז איך זה קרה ?

 למשתמש רגיל תמיד היית גישה לבקרים שלו ולמחיקה .
לגבי מחיקת תוכנה , לא יכול להיות שלאחר מחיקת בקר גם התוכנה נמחקת . כנראה לקוח מתבלבל .
ממתי בקרים נמחקו ?

**Comment by agrologic-repo** [comment]
@daniels100  דניאל ,

האם אפשר לסגור את זה ?

**Comment by daniels100** [comment]
לבנתיים לא היו בעיות כאלו אני סוגר את זה
