### ISSUE TITLE
וואבציק מראה באופו שגוי טמפרטורת חוץ כאשאר היא מינוס

### ISSUE THREAD

**Issue by daniels100** [agrologic-repo/webchick-server#35]
קיבלנו תלונות מלקוחות על הצגה שגוי של טמפרטורת חוץ כאשר היא במינוס
הפעלתי אצלינו בקר עם טמפרטורת חוץ (-5.5) ובוצ'יק מציג לי (-55)
הפעלתי LOG על הסלינג שלי ורואים שהבקר שולח טמפרטורה תקינה ,והוואבציק לא מציג נקודה עשרונית
טייפ של טמפרטורת חוץ 7203
מצורף דוח של הסלינג שלי
![בעיה בטמפרטוה חוץ](https://user-images.githubusercontent.com/45685799/73828572-31c3a680-480a-11ea-977c-9a4643db75c0.png)

**Comment by daniels100** [comment]
[WABCHICK-LOG.txt](https://github.com/agrologic-repo/webchick-server/files/4158559/WABCHICK-LOG.txt)

**Comment by agrologic-repo** [comment]
בעיה טופלה . העלתי גרסה 6.8.0  של ווב .
