### ISSUE TITLE
בעיית סיסמה

### ISSUE THREAD

**Issue by daniels100** [agrologic-repo/webchick-server#36]
מדי פעם מתקבל אצלינו תלונה של לקוחות שהם לא מצליחים להיכנס למערכת עם הסיסמה שלהם ,
כאשר אני נכנס לחשבון שלהם אני רואה שהסיסמה שונתה לסיסמה מוזרה כמתואר בתמונה
![בעיית סיסמה](https://user-images.githubusercontent.com/45685799/74600600-694d1100-509c-11ea-9238-177e3a1f7b0c.png)

**Comment by agrologic-repo** [comment]
זהו סוג של בעיה שקשורה לניתור . כרגע אני עובד על הוספת לוג כך שאפשר יהיה לעשות עליו אנליטיקה . או לאתר האם משתמש כל שהו עשה שינוי . 
בכל מקרה לא ראיתי בקוד שיש אפשרות לבאג שמשנה סיסמה 

בנוסף בוצע שינוי ססמה לססמה מקורית

**Comment by agrologic-repo** [comment]
בוצע שינוי ססמה לססמה מקורית

**Comment by agrologic-repo** [comment]
@daniels100  דניאל ,
הוספתי לוג כל פעם שיתבצע שינוי סיסמה אפשר יהיה לבדוק מתי זה נעשה .
אם יהיו עוד מקרים בבקשה תרשום שם משתמש למעכב .
