### ISSUE TITLE
בעיית היסטוריה 

### ISSUE THREAD

**Issue by daniels100** [agrologic-repo/webchick-server#37]
לקוח בשם Betze-Emek-Hela
לול 1 נמצא ביום גידול 145 ההיסטוריה לא מתקדמת תקועה ביום 139

**Comment by agrologic-repo** [comment]
האם היסטוריה עדיין לא מתקדמת ?

**Comment by daniels100** [comment]
Betze-Emek-Hela
לא מראה היסטוריה בכלל , לא יכול לראות אם זה מתקדם


Thank you and best regards,
Daniel Shlomovich|Technical Support
Office Tel: 972-9-8626089
           Fax: 972-9-8626087
www.agrologic.com<http://www.agrologic.com/>

[AgroLogic]

**Comment by agrologic-repo** [comment]
@daniels100 

היסטוריה תוקנה 

![image](https://user-images.githubusercontent.com/2639323/81223762-39544080-8fef-11ea-8edc-ce1923bba908.png)

**Comment by agrologic-repo** [comment]
@daniels100 

יש בעיה אחרת שזה שמות נתונים שחוזרים .
יש לתקן את זה .

![image](https://user-images.githubusercontent.com/2639323/81224001-a8319980-8fef-11ea-9906-246673fc0400.png)
