### ISSUE TITLE
 Betze-Emek-Hela בעיית היסטוריה בעמק האלה 

### ISSUE THREAD

**Issue by daniels100** [agrologic-repo/webchick-server#46]
הלול נמצא ביום 230
ההיסטוריה תקוע על יום 222
במעקב על הלול ניתן לראות שיש שאלות לגבי יום 223 וגם מחזיר תשובה אבל משום מה עדיין לא מקדם יום היסטוריה
![בעיית היסטוריה](https://user-images.githubusercontent.com/45685799/82993468-43bf9400-a009-11ea-89ac-98a26b6fe0d2.png)

**Comment by agrologic-repo** [comment]
ראיתי את הבעיה . וטיפלתי בה כבר .
@daniels100  לבדיקתך .....

**Comment by daniels100** [comment]
זה עובד אני סוגר
