### ISSUE TITLE
לול בשם qlacitarum

### ISSUE THREAD

**Issue by daniels100** [agrologic-repo/webchick-server#9]
לא ניתן במקרה הזה להוסיף חוות 
דבר נוסף לא ניתן לשנות בקר קיים מECM12 לIMAGE
![p1](https://user-images.githubusercontent.com/45685799/52056192-3c4dbf00-256a-11e9-88a4-1fa0f2afc8fa.png)
![p2](https://user-images.githubusercontent.com/45685799/52056210-48d21780-256a-11e9-9498-1ffdc2b293fe.png)

**Comment by agrologic-repo** [comment]
בעיה תוקנה. ניתן גם להוסיף בקר חדש  וגם לשנות סוג בקר קיים
